### ISSUE TITLE
[Web worker]

### ISSUE THREAD

**Issue by shprink** [AngularToulouse/meetups#10]

**Comment by maxdow** [comment]
Appliqué a angular ou en général ?

**Comment by shprink** [comment]
Applique a Angular mobile ou Ionic ouai, tu es interese ?

**Comment by shprink** [comment]
Ya pas vraiment de docs encore sur tout ca, c'est encore experimental

**Comment by maxdow** [comment]
Je l'utilise en standalone et à minima alors je ne pense pas être le mieux placé pour ça :/

**Comment by shprink** [comment]
@maxdow si tu arrive a faire une intro sur ca et que tu montre un cas d'utilisation sur ng2 ou ionic ca pourrait etre cool :)

**Comment by shprink** [comment]
tu es LA reference sur Toulouse ;)

**Comment by maxdow** [comment]
ng2 faudrait encore que je l'installe :p . Je l'utilise pour l'instant sur une appli ng1 mais le use case serait le même ( c'est un pooler genre heartbeat, le webworker est là pour le fun ). 
Si jamais je fais qq chose ce n'est pas avant 2 mois de toute façon mais ..pourquoi pas ;)

**Comment by maxdow** [comment]
Un use case que je trouve interessant est le parsing de doc coté client ( et il me semble que c'est le cas pour la doc du site ng1 )
