### ISSUE TITLE
[Angular-CLI] - Kevin Davin

### ISSUE THREAD

**Issue by davinkevin** [AngularToulouse/meetups#11]
Présentation sur l'outil de démarrage de la CLI. 

Je réserve un slot libre lors du prochain meetup (certainement après la période estivale).

[Vidéos disponible sur Youtube](https://youtu.be/aR_Ueqz2Zf8)
[Slides de la présentation](https://davinkevin.github.io/angular2cli-presentation/#/intro)
[Live Coding Repository](https://github.com/davinkevin/angular2-cli-demo/) | [Github-Pages](https://davinkevin.github.io/angular2-cli-demo/)

**Comment by Chabane** [comment]
Intégrer angular2-polymer sur angular-cli?

**Comment by davinkevin** [comment]
Je peux regarder, mais le but de la présentation est de ce centrer sur la CLI, de voir comment intégrer 1 ou 2 libs tierces... ce que j'ai déjà fait, donc je vais voir si Angular2-Polymer peut être fait sans trop déborder du timing et du sujet.

**Comment by davinkevin** [comment]
Ajouts des liens vers les supports
