### ISSUE TITLE
[Ahead Of Time compilation aka AOT]

### ISSUE THREAD

**Issue by shprink** [AngularToulouse/meetups#17]
pour aider => http://slides.com/wassimchegham/demystifying-ahead-of-time-compilation-in-angular-2-aot-jit#/

**Comment by davinkevin** [comment]
Ce support peux aussi aider : https://www.youtube.com/watch?v=kW9cJsvcsGo

Perso, j'aurai bien envie de le prendre, sur un format court (~15 min).

**Comment by shprink** [comment]
Quand tu veux @davinkevin !

**Comment by davinkevin** [comment]
Allé, je prend... après il faut voir pour quand 😄

**Comment by davinkevin** [comment]
Side note : 
- https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#q-angular-compiler
