### ISSUE TITLE
[Aurelia, ce qu'aurait du être Angular 2 dans un monde parallèle] | Hadrien Lanneau

### ISSUE THREAD

**Issue by shprink** [AngularToulouse/meetups#18]

**Comment by hadrienl** [comment]
"Aurelia, ce qu'aurait du être Angular 2 dans un monde parallèle"

**Comment by maxdow** [comment]
C'est une prez d'Aurelia enfait ?

**Comment by shprink** [comment]
@hadrienl merci d'avoir propose, on en a discute avec l'equipe et ca peu etre plus sa place dans un ToulouseJS @maxdow.
