### ISSUE TITLE
Experience Feedback Dart in Production & How to use JS librairies in  Dart / AngularDart

### ISSUE THREAD

**Issue by bwnyasse** [AngularToulouse/meetups#19]
L'idée serait  
- de faire un tour de quelques vrais applications notables qui utilisent Dart en production 
- mon retour d'expérience sur les applications Dart que j'ai envoyé en production ( 2 grands publics : https://www.picknschool.com , https://www.wicanplay.com   et une en interne dans mon entreprise qui vient d'à peine d'être mise en prod )
- l'utilisation incontournable des librairies JS si on veut faire une vraie application Web avec Dart

**Comment by shprink** [comment]
On se reserve ca pour debut 2017? 

Pour Janvier, Fevrier tu pense pouvoir avoir un talk de 30min?

**Comment by bwnyasse** [comment]
Ok pour 2017. Oui ce serait possible de préparer un talk de 30min

**Comment by shprink** [comment]
Super, c'est cool ce que tu fais en tout cas ;)

**Comment by shprink** [comment]
Salut,

On partirais sur le 26 Janvier. Seras tu disponible?

**Comment by bwnyasse** [comment]
Salut @shprink ,

Ok, je me note ça.  En principe, je suis disponible ce jeudi 26/01

**Comment by shprink** [comment]
L'event sera annoncé sur le GDG et ce sera plus 45 min (avec question) mais si tu fais moins c'est pas grave ;) https://www.meetup.com/GDG-Toulouse/

**Comment by bwnyasse** [comment]
Ok 
je pense que 45 min ca devrait aller avec les petites démo
