### ISSUE TITLE
[Dart intro] - Jérôme Beigbeder

### ISSUE THREAD

**Issue by shprink** [AngularToulouse/meetups#2]
[Vidéos disponible sur Youtube](https://youtu.be/3dbJKrwaoY4)
[Slides de la présentation](https://docs.google.com/presentation/d/1O2AztOQ9UXIa8K83QwEpcYTvJxtznT1RN9wVvLNvQJA/edit?usp=sharing)
Live Coding Repository: pending...

**Comment by jbeigbeder** [comment]
Je suis intéressé par le sujet.
Qu'elles sont les modalités:
- date
- durée
- contour (totalement libre ou délimitations précises)

Merci

**Comment by shprink** [comment]
Super!

La date sera courant Septembre a priori. 

Nous sommes sur un format de 30 min max incluant questions.

Pour le contour du sujet il est totalement libre oui, il conviendra de nous donner un plan et une description en avance pour la communication.

**Comment by bwnyasse** [comment]
Hello  @jbeigbeder 

Kevin Segaud ( @Kleak ) et moi , sommes aussi intéressés par le sujet. En effet , nous étions entrain de nous synchroniser pour voir ce qu'on pouvait proposer comme format et contenu pour une présentation. 

Dans ce sens, nous pouvons peut-être voir ensemble comment s'organiser pour tout ça ? S'il ya plusieurs personnes intéressées par des talk sur 'Dart' , ça pourrait nous faire plein de sujets différents à traiter :+1:

**Comment by jbeigbeder** [comment]
Bonjour à tous,

Grossiėrement, je souhaiterai présenter le langage Dart (vraiment très vite, je ne veux pas entrer dans le détail de la syntaxe ou des APIs, mais ca pourrait être l'objet d'un autre talk). Mais je voudrai plutôt mettre l'accent sur ce qui rend l'utilisation d'Angular 2 avec Dart spécifique et sympatique:
- Utilisation de dart:async et de dart:html en lieu et place de ce qui est proposé pour Typescript et JavaScript 
- la plateforme dart / pub pour la construction des livrables

Tout ceci dans l'optique d'expliquer pourquoi Dart permet d'aborder Angular 2 simplement surtout pour ceux qui n'ont pas un gros background dans le monde JavaScript. 

PS : je viens du monde Java

J'attends vos retours.

**Comment by jbeigbeder** [comment]
Oups l'intitulé de l'issue à changé?

**Comment by shprink** [comment]
![image](https://cloud.githubusercontent.com/assets/1388706/16689634/20d3fa9c-4524-11e6-9482-7cdd45deb4d7.png)

C'est pareil le label est bien angular2:

![image](https://cloud.githubusercontent.com/assets/1388706/16689642/32e2df64-4524-11e6-8212-0b1918208e75.png)

**Comment by kevin-sakemaer** [comment]
On avait dans l'optique de faire une presentation en 2 ou 3 parties
1. Intro qu'est-ce que Dart
2. Use case en archi micro service : client (en angular2 bien sur) + serveur
3. _bonus: une app creer avec flutter si il reste du temps_

Du coup @jbeigbeder si cela te dit de faire la premiere parti c'est tout a fait envisagable

**Comment by shprink** [comment]
Du coup on pourrait partir sur un sujet par meetup non pour ne pas trop se disperser? 30min avec questions ca passe tres vite.

**Comment by jbeigbeder** [comment]
@Kleak et @bwnyasse, votre programme me semble intéressant. 
Je veux bien m'occuper de l'introduction au langage Dart.

@shprink , une partie par meetup est, je pense aussi, une bonne idée.
En plus comme ça, on s'inscrit dans la durée. Ce qui peut titiller la curiosité des autres participants autour de Dart.

**Comment by shprink** [comment]
Ok super, je vous laisse donc collaborer ensemble si vous voulez reflechir au plan de l'intro pour Septembre :)

**Comment by kevin-sakemaer** [comment]
@jbeigbeder je tinvite a venir sur le slack comme ca on parle de tous ca labas, histoire de pas embeter tout le monde ici, ya un salon toulousedart 😉

**Comment by shprink** [comment]
@jbeigbeder on a besoin de tes dispos pour le meetup (cf Slack). Merci

**Comment by shprink** [comment]
Les slides https://docs.google.com/presentation/d/1O2AztOQ9UXIa8K83QwEpcYTvJxtznT1RN9wVvLNvQJA/edit?usp=sharing
