### ISSUE TITLE
[La programmation réactive pour les nuls] Bruno Baia

### ISSUE THREAD

**Issue by bbaia** [AngularToulouse/meetups#21]
La programmation réactive ('Reactive Programming' en anglais) est un paradigme de programmation dont on entend parler de plus en plus aujourd'hui et qui devient indispensable de comprendre si on souhaite développer des applications Web modernes.
J'essaierai de démystifier tout ça avec des exemples concrets et son utilisation dans AngularJS 2.

Je vous propose une session d'1h sur le sujet, avec pas mal de démos.

**Comment by shprink** [comment]
Bonjour,

Merci pour ta proposition, je pense que c'est un sujet passionnant. Nous sommes sur un format de deux fois 30-45min normalement mais on peut reflechir a ne faire que ce sujet.

As tu deja fait des talks a des meetups ou conferences?

**Comment by bbaia** [comment]
Bonjour Julien,

Uniquement en interne dans les entreprises.
Jamais eu l'occasion en public.
